// Generated by CoffeeScript 1.6.3
/*
  Module dependencies
*/


(function() {
  var app, express, http, path, routes;

  express = require('express');

  routes = require('./routes/clone');

  http = require('http');

  path = require('path');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.set('views', "" + __dirname + "/views");

  app.set('view engine', 'hjs');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(express.cookieParser('newellls'));

  app.use(express.session());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, 'public')));

  if (app.get('env' === 'development')) {
    app.use(express.errorHandler());
  }

  app.post('/clone/:landingPage/:domain', routes.clone);

  (http.createServer(app)).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + (app.get('port')));
  });

}).call(this);
