// Generated by CoffeeScript 1.6.3
(function() {
  var Cloner, config;

  Cloner = require('../src/cloner');

  config = require('../src/config');

  exports.clone = function(req, res) {
    var cloner, config_env, data, domain, error, lp;
    lp = req.params.landingPage;
    domain = req.params.domain;
    config_env = config[req.app.get('env')];
    config_env['all'] = config['all'];
    data = req.body.data;
    cloner = new Cloner(data, config_env, lp, domain);
    try {
      return cloner.clone(function() {
        var status;
        status = 'success';
        return res.json({
          status: status,
          domain: "" + domain + config_env.domain
        });
      });
    } catch (_error) {
      error = _error;
      return res.json({
        status: "error"
      });
    }
  };

}).call(this);
