// Generated by CoffeeScript 1.6.3
var Cloner, config;

Cloner = require('../src/cloner');

config = require('../src/config');

exports.clone = function(req, res) {
  var cloner, data, domain, lp, _config;
  req.connection.setTimeout(10 * 60 * 1000);
  lp = req.params.landingPage;
  domain = req.params.domain;
  _config = {};
  _config = config['products'][lp];
  _config['env'] = config[req.app.get('env')];
  data = req.body.data;
  cloner = Cloner.create(data, _config, lp, domain);
  cloner.clone();
  cloner.on('success', function(domain) {
    return res.json({
      status: 'success',
      domain: "" + domain + _config.env.domain
    });
  });
  return cloner.on('error', function(err, type, args) {
    console.log(err, type, args);
    return res.json(500, {
      status: 'error',
      error: {
        type: type,
        code: err.code,
        message: err.toString()
      }
    });
  });
};
