// Generated by CoffeeScript 1.6.3
(function() {
  var Cloner, EventEmitter, exec, fs, hogan, mkdirp, mysql,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  fs = require('fs-extra');

  mkdirp = require('mkdirp');

  hogan = require('hogan.js');

  mysql = require('mysql2');

  exec = (require('child_process')).exec;

  EventEmitter = (require('events')).EventEmitter;

  Cloner = (function(_super) {
    __extends(Cloner, _super);

    function Cloner(vars, config, lp, subdomain) {
      this.vars = vars;
      this.config = config;
      this.lp = lp;
      this.subdomain = subdomain;
      EventEmitter.call(this);
      this.baseSQL = "db.sql";
      this.dbCompiled = null;
    }

    Cloner.prototype.clone = function(callback) {
      var _this = this;
      this.callback = callback != null ? callback : null;
      this.dest = "" + this.config.destDir + "/" + this.subdomain + "/htdocs";
      return mkdirp(this.dest, function(err) {
        if (err) {
          _this._handleError(err, 'mkdir', _this.dest);
          return callback(err);
        }
        return fs.copy(_this.config.srcDir, _this.dest, function(err) {
          if (err) {
            _this._handleError(err, 'copy', _this.config.srcDir, _this.dest);
            return callback(err);
          }
          return _this._compileDb(function() {
            return _this._createDb(function() {
              return _this._compileConfig(function() {
                return _this.emit('success', _this.subdomain);
              });
            });
          });
        });
      });
    };

    Cloner.prototype._connect = function(options) {
      var config;
      if (options == null) {
        options = {};
      }
      config = {
        user: this.config.db.user,
        password: this.config.db.password,
        multipleStatements: true
      };
      return this.conn = mysql.createConnection(config);
    };

    Cloner.prototype._createDb = function(callback) {
      var dbName,
        _this = this;
      dbName = "lp_" + this.subdomain;
      this._connect();
      return this.conn.query("CREATE DATABASE " + dbName + " CHARACTER SET utf8 COLLATE utf8_general_ci", function(err, result) {
        if (err) {
          _this._handleError(err, 'createdb', dbName);
          return callback(err);
        }
        return _this._mysqlCmd(dbName, "" + _this.dest + "/" + _this.baseSQL, function(err, stdout, stderr) {
          if (err) {
            _this._handleError(err, 'sourcedb', stderr);
            return callback(err);
          }
          return _this.conn.end(function(err) {
            return callback();
          });
        });
      });
    };

    Cloner.prototype._compileDb = function(callback) {
      var _this = this;
      return fs.readFile("" + this.dest + "/" + this.baseSQL, {
        encoding: 'utf8'
      }, function(err, data) {
        var template;
        if (err) {
          _this._handleError(err, 'compiledb_read');
          return callback(err);
        }
        template = hogan.compile(data);
        _this.dbCompiled = template.render(_this.vars);
        return fs.writeFile("" + _this.dest + "/" + _this.baseSQL, _this.dbCompiled, function(err) {
          if (err) {
            _this._handleError(err, 'compiledb_write');
            return callback(err);
          }
          return callback();
        });
      });
    };

    Cloner.prototype._compileConfig = function(callback) {
      var config,
        _this = this;
      config = "" + this.dest + "/" + this.config.all.configFile;
      return fs.readFile("" + this.config.srcDir + "/" + this.config.all.configFile, {
        encoding: 'utf8'
      }, function(err, data) {
        var template, vars;
        if (err) {
          _this._handleError(err, 'compileconfig_read');
          return callback(err);
        }
        template = hogan.compile(data);
        vars = {
          dbUser: _this.config.db.user,
          dbName: "lp_" + _this.subdomain,
          dbPassword: _this.config.db.password
        };
        return fs.writeFile(config, template.render(vars), function(err) {
          if (err) {
            _this._handleError(err, 'compileconfig_write');
            return callback(err);
          }
          return callback();
        });
      });
    };

    Cloner.prototype._mysqlCmd = function(db, file, callback) {
      return exec("mysql -u" + this.config.db.user + " -p" + this.config.db.password + " " + db + " < " + file, callback);
    };

    Cloner.prototype._handleError = function() {
      var args, err, type;
      err = arguments[0], type = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      return this.emit('error', err, type, {
        args: args
      });
    };

    return Cloner;

  })(EventEmitter);

  module.exports = Cloner;

}).call(this);
