// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    development: {
      srcLp: "/tmp/landingpage/wordpress",
      destLp: "/tmp/clients",
      domain: ".prod.finderit.com"
    },
    prodduction: {
      srcLp: "/var/www/landingpages/wordpress",
      destLp: "/var/www/clients",
      domain: ".prod.finderit.com"
    }
  };

}).call(this);
