// Generated by CoffeeScript 1.6.3
var Utils, exec,
  __slice = [].slice;

exec = require('child_process').exec;

Utils = {
  HandleError: function() {
    var args, err, type;
    err = arguments[0], type = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    return this.emit('error', err, type, {
      args: args
    });
  },
  GetUid: function(userOrGroup, type, cb) {
    if (userOrGroup == null) {
      userOrGroup = "";
    }
    if (type !== 'u' && type !== 'g') {
      throw new Error('Invalid type');
    }
    return exec("id -" + type + " " + userOrGroup, function(err, stdout, stderr) {
      return cb(err, stdout);
    });
  }
};

module.exports = Utils;
