// Generated by CoffeeScript 1.7.1
(function() {
  var BaseProduct, Elgg, Joomla, Limesurvey, Moodle, Prestashop, Vtiger, Wordpress, utils,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseProduct = require('./BaseProduct');

  utils = require('../utils');

  Wordpress = (function(_super) {
    __extends(Wordpress, _super);

    function Wordpress(config, vars, subdomain, landingpage, destDir) {
      Wordpress.__super__.constructor.call(this, config, vars, subdomain, landingpage, destDir);
      this.on('compile.success', (function(_this) {
        return function() {
          return _this.updateDb();
        };
      })(this));
    }

    Wordpress.prototype.updateDb = function() {
      var conn;
      conn = this._connect({
        database: this.dbname
      });
      return conn.execute('UPDATE wp_options SET option_value = ? WHERE option_name = ?', ["http://" + this.fqdn, 'siteurl'], (function(_this) {
        return function(err, res) {
          if (err) {
            utils.HandleError.call(_this, err, 'updatedb_err');
            return;
          }
          return conn.execute('UPDATE wp_options SET option_value = ? WHERE option_name = ?', ["http://" + _this.fqdn, 'home'], function(err, res) {
            if (err) {
              utils.HandleError.call(_this, err, 'updatedb_err');
              return;
            }
            return conn.end(function() {
              return _this.emit('success', _this.fqdn);
            });
          });
        };
      })(this));
    };

    return Wordpress;

  })(BaseProduct);

  Joomla = (function(_super) {
    __extends(Joomla, _super);

    function Joomla(config, vars, subdomain, landingpage, destDir) {
      Joomla.__super__.constructor.call(this, config, vars, subdomain, landingpage, destDir);
      this.configFileVars['logDir'] = this._getPath(this.destDir, 'logs');
      this.configFileVars['tmpDir'] = this._getPath(this.destDir, 'tmp');
    }

    return Joomla;

  })(BaseProduct);

  Limesurvey = (function(_super) {
    __extends(Limesurvey, _super);

    function Limesurvey() {
      return Limesurvey.__super__.constructor.apply(this, arguments);
    }

    return Limesurvey;

  })(BaseProduct);

  Moodle = (function(_super) {
    __extends(Moodle, _super);

    function Moodle() {
      return Moodle.__super__.constructor.apply(this, arguments);
    }

    return Moodle;

  })(BaseProduct);

  Prestashop = (function(_super) {
    __extends(Prestashop, _super);

    function Prestashop() {
      return Prestashop.__super__.constructor.apply(this, arguments);
    }

    return Prestashop;

  })(BaseProduct);

  Vtiger = (function(_super) {
    __extends(Vtiger, _super);

    function Vtiger() {
      return Vtiger.__super__.constructor.apply(this, arguments);
    }

    return Vtiger;

  })(BaseProduct);

  Elgg = (function(_super) {
    __extends(Elgg, _super);

    function Elgg(config, vars, subdomain, landingpage, destdir) {
      Elgg.__super__.constructor.call(this, config, vars, subdomain, landingpage, destdir);
      this.on('compile.success', (function(_this) {
        return function() {
          return _this.updateDb();
        };
      })(this));
    }

    Elgg.prototype.updateDb = function() {
      var conn;
      conn = this._connect({
        database: this.dbname
      });
      return conn.execute('UPDATE `elgg_datalists` SET `value` = ? WHERE `name` = "path"', ["" + this.destDir + "/"], (function(_this) {
        return function(err, res) {
          if (err) {
            utils.HandleError.call(_this, err, 'updatedb_err');
          }
          return conn.execute('UPDATE `elgg_datalists` SET `value` = ? WHERE `name` = "dataroot"', ["" + _this.baseDir + "/elgg_data/"], function(err, res) {
            if (err) {
              utils.HandleError.call(_this, err, 'updatedb_err');
            }
            return conn.execute('UPDATE `elgg_sites_entity` SET `url` = ?', [_this.fqdn], function(err, res) {
              if (err) {
                utils.HandleError.call(_this, err, 'updatedb_err');
              }
              return conn.execute("UPDATE elgg_metastrings set string = ? WHERE id = (SELECT value_id from elgg_metadata where name_id =\n(SELECT * FROM (SELECT id FROM elgg_metastrings WHERE string = 'filestore::dir_root') as ms2) LIMIT 1)", ["" + _this.baseDir + "/elgg_data/"], function(err, res) {
                if (err) {
                  utils.HandleError.call(_this, err, 'updatedb_err');
                }
                return conn.end(function(err) {
                  if (err) {
                    utils.HandleError.call(_this, err, 'updatedb_err');
                  }
                  return _this.emit('success', _this.fqdn);
                });
              });
            });
          });
        };
      })(this));
    };

    return Elgg;

  })(BaseProduct);

  module.exports.Wordpress = Wordpress;

  module.exports.Joomla = Joomla;

  module.exports.Limesurvey = Limesurvey;

  module.exports.Moodle = Moodle;

  module.exports.Prestashop = Prestashop;

  module.exports.Vtiger = Vtiger;

  module.exports.Elgg = Elgg;

}).call(this);

//# sourceMappingURL=products.map
